# Generated by Django 4.2.27 on 2026-06-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MachineApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('country', models.CharField(max_length=255)),
                ('message', models.TextField(max_length=1000)),
            ],
        ),
    ]
