# Generated by Django 4.2.27 on 2026-06-20 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MachineApp', '0002_quate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quate',
            new_name='Quote',
        ),
    ]
