# Generated by Django 4.2.27 on 2026-06-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MachineApp', '0003_rename_quate_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
