# Generated by Django 4.2.27 on 2026-10-08 12:31

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MachineApp', '0004_alter_quote_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='videos/'),
        ),
    ]
